# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- "*"

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Web_Api_Functions_Job
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    # - script: npm install
    #   displayName: 'WEB: npm install'
    #   workingDirectory: conways-game-of-life.ng

    # - script: npm run builddev -- --output-path $(Build.ArtifactStagingDirectory)/conways-game-of-life.ng/dev
    #   displayName: 'WEB: build angular app DEV'
    #   workingDirectory: conways-game-of-life.ng

    # - script: npm run buildprod -- -c=production --output-path $(Build.ArtifactStagingDirectory)/conways-game-of-life.ng/prod
    #   displayName: 'WEB: build angular app PROD'
    #   workingDirectory: conways-game-of-life.ng

    - script: dotnet restore
      displayName: 'restore packages'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests and Collect Code Coverage'
      inputs:
        command: test
        projects: '**/*tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
        displayName: 'execute all tests'

    - script: dotnet publish $(Build.SourcesDirectory)/conways-game-of-life.afn/conways-game-of-life.afn.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/conways-game-of-life.afn
      displayName: 'FUNCTIONS: publish build artifacts'

    - task: PublishBuildArtifacts@1 
